version: '3.3'
services:
  jekyll:
    image: jekyll/minimal:pages
    command: jekyll serve --watch --incremental --drafts --unpublished --livereload
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
