version: '3.3'
services:
  jekyll:
    image: jekyll/minimal:pages
    command: jekyll serve --watch --incremental --drafts --unpublished
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
